import {PropsWithChildren} from "react";
import type { Metadata } from "next";
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: PropsWithChildren) {

  return (
    <html lang="ko">
      <body className="overflow-y-scroll max-h-svh">
      {children}
      </body>
    </html>
  );
}
